describe('Given the CreateOffer Service', () => {
  describe('When page loads', () => {
    it('Then should fill the form and create a job offer', () => {
      cy.visit('http://localhost:8081/#/app/jobs/')
      cy.wait(3000)
      cy.get('a').contains('Crear Oferta').click()
      cy.url().should('include', '/app/jobs/add')
      cy.get('input[name="title"]').should('exist')
      cy.get('input[name="title"]')
        .type('Job Test 1')
        .should('have.value', 'Job Test 1')
      cy.get('input[name = "state"]').should('exist')
      cy.get('input[name = "state"]')
        .type('Distrito Capital')
        .should('have.value', 'Distrito Capital')
      cy.get('input[name = "city"]')
        .type('Caracas')
        .should('have.value', 'Caracas')
      cy.get('input[name = "street1"]').should('exist')
      cy.get('input[name = "street1"]')
        .type('Lorem ipsum dolor sit amet, consectetur.')
        .should('have.value', 'Lorem ipsum dolor sit amet, consectetur.')
      cy.get('input[name = "street2"]').should('exist')
      cy.get('input[name = "street2"]')
        .type('Nullam eget gravida mi, a sodales urna')
        .should('have.value', 'Nullam eget gravida mi, a sodales urna')
      cy.get('input[name = "zip"]').type('1030').should('have.value', '1030')
      cy.get('textarea[name = "special_requirements"]')
        .type(
          'Ut ornare rutrum nibh, vitae accumsan justo porta eget. Donec bibendum quis ligula sed ultrices. Mauris hendrerit sed ipsum ac lobortis.'
        )
        .should(
          'have.value',
          'Ut ornare rutrum nibh, vitae accumsan justo porta eget. Donec bibendum quis ligula sed ultrices. Mauris hendrerit sed ipsum ac lobortis.'
        )
      cy.get('input[id="dead_line"]').clear({ force: true })
      cy.get('input[id="dead_line"]')
        .type('26/08/2021')
        .should('have.value', '26/08/2021')
      cy.get('input[id="schedules1"]').clear({ force: true })
      cy.get('input[id="schedules1"]')
        .type('16/08/2021 08:00 AM')
        .should('have.value', '16/08/2021 08:00 AM')
      cy.get('input[id="schedules2"]').clear({ force: true })
      cy.get('input[id="schedules2"]')
        .type('16/08/2021 11:00 AM')
        .should('have.value', '16/08/2021 11:00 AM')
      cy.get('.schedule-list_btn__add')
        .contains('Agregar')
        .click({ force: true })
      cy.get('div[name="skills"]').click()
      cy.get('.p-multiselect-items').find('li').first().as('first-skill')
      cy.get('@first-skill').click()
      cy.get('input[name="hourly_rate"]').clear({ force: true })
      cy.get('input[name="hourly_rate"]').type(20).should('have.value', '20')
      cy.get('input[name="duration"]').clear({ force: true })
      cy.get('input[name="duration"]').type(3).should('have.value', '3')
      cy.get('.p-button').contains('Agregar Oferta').click()
      cy.wait(3000)
    })
  })
})
